workflows:
  android-webview-release:
    name: Build Android WebView APK
    environment:
      image: ubuntu-20.04
      java: 11
    scripts:
      - echo "Building APK..."
      - ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
